-- begin BOOKSTORE_USER
alter table BOOKSTORE_USER add constraint FK_BOOKSTORE_USER_ON_ROLE foreign key (ROLE_ID) references BOOKSTORE_ROLE(ID)^
create unique index IDX_BOOKSTORE_USER_UK_LOGIN on BOOKSTORE_USER (LOGIN) where DELETE_TS is null ^
create index IDX_BOOKSTORE_USER_ON_ROLE on BOOKSTORE_USER (ROLE_ID)^
-- end BOOKSTORE_USER
-- begin BOOKSTORE_BASKET
alter table BOOKSTORE_BASKET add constraint FK_BOOKSTORE_BASKET_ON_USER foreign key (USER_ID) references BOOKSTORE_USER(ID)^
create index IDX_BOOKSTORE_BASKET_ON_USER on BOOKSTORE_BASKET (USER_ID)^
-- end BOOKSTORE_BASKET
-- begin BOOKSTORE_BOOK
alter table BOOKSTORE_BOOK add constraint FK_BOOKSTORE_BOOK_ON_GENRE foreign key (GENRE_ID) references BOOKSTORE_GENRE(ID)^
alter table BOOKSTORE_BOOK add constraint FK_BOOKSTORE_BOOK_ON_AUTHOR foreign key (AUTHOR_ID) references BOOKSTORE_AUTHOR(ID)^
create index IDX_BOOKSTORE_BOOK_ON_GENRE on BOOKSTORE_BOOK (GENRE_ID)^
create index IDX_BOOKSTORE_BOOK_ON_AUTHOR on BOOKSTORE_BOOK (AUTHOR_ID)^
-- end BOOKSTORE_BOOK
-- begin BOOKSTORE_STAFF
alter table BOOKSTORE_STAFF add constraint FK_BOOKSTORE_STAFF_ON_ROLE foreign key (ROLE_ID) references BOOKSTORE_ROLE(ID)^
create unique index IDX_BOOKSTORE_STAFF_UK_LOGIN on BOOKSTORE_STAFF (LOGIN) where DELETE_TS is null ^
create index IDX_BOOKSTORE_STAFF_ON_ROLE on BOOKSTORE_STAFF (ROLE_ID)^
-- end BOOKSTORE_STAFF
