-- begin BOOKSTORE_BASKET
alter table BOOKSTORE_BASKET add constraint FK_BOOKSTORE_BASKET_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table BOOKSTORE_BASKET add constraint FK_BOOKSTORE_BASKET_ON_BOOK foreign key (BOOK_ID) references BOOKSTORE_BOOK(ID)^
create index IDX_BOOKSTORE_BASKET_ON_USER on BOOKSTORE_BASKET (USER_ID)^
create index IDX_BOOKSTORE_BASKET_ON_BOOK on BOOKSTORE_BASKET (BOOK_ID)^
-- end BOOKSTORE_BASKET
-- begin BOOKSTORE_BOOK
alter table BOOKSTORE_BOOK add constraint FK_BOOKSTORE_BOOK_ON_GENRE foreign key (GENRE_ID) references BOOKSTORE_GENRE(ID)^
alter table BOOKSTORE_BOOK add constraint FK_BOOKSTORE_BOOK_ON_AUTHOR foreign key (AUTHOR_ID) references BOOKSTORE_AUTHOR(ID)^
create index IDX_BOOKSTORE_BOOK_ON_GENRE on BOOKSTORE_BOOK (GENRE_ID)^
create index IDX_BOOKSTORE_BOOK_ON_AUTHOR on BOOKSTORE_BOOK (AUTHOR_ID)^
-- end BOOKSTORE_BOOK
