alter table BOOKSTORE_BOOK add constraint FK_BOOKSTORE_BOOK_ON_AUTHOR foreign key (AUTHOR_ID) references BOOKSTORE_AUTHOR(ID);
create index IDX_BOOKSTORE_BOOK_ON_AUTHOR on BOOKSTORE_BOOK (AUTHOR_ID);
